name: say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: echo "Hello, world!"
      - run: |
          echo "Hello, world"
      - name: Dime la fecha
        run: date
      - run: ls -la
      