name: Deploymen Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 #Esto lo que hace es que solo se trae el ultimo commit, para hacer el git checkout mucho mas rapido. 
      - uses: actions/setup-node@v5
        with:
          node-version: 18
        name: Install dependencies
      - run: npm install --no-audit --no-fund --no-optional
      - name: Lint code
        run: npm run eslint
      - name: Build project
        run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
      - name: test project
        run: npm test
      - name: E2E tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000